using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Entities
{
    public class Order
    {
        public long Id { get; set; }
        // Mamad-2023-02-18-1001
        // DKC-2514011129
        // It Generated by database
        public string OrderNumber { get; set; }
        public ICollection<PersonOrder> PersonOrders { get; set; }
    }
}
